recipes-samples/packagegroups: Fixes order to set PACKAGE_ARCH
Fixes,

ERROR: Please ensure recipe
/srv/oe/build/conf/../../layers/meta-rpb/recipes-samples/packagegroups/packagegroup-rpb.bb
sets PACKAGE_ARCH before inherit packagegroup

In,

https://ci.linaro.org/job/lt-qcom-openembedded-rpb-rocko/DISTRO=rpb,MACHINE=dragonboard-410c,label=docker-stretch-amd64/95/console

Signed-off-by: Aníbal Limón <anibal.limon@linaro.org>
(cherry picked from commit f0471c292516be138a588da978dcfe017195f0e4)