ltp: Remove license for pounder21, which has been removed
As of commit 54d3e8696798, LTP has removed pounder21 stating
that "[i]t's is obsolete, not being built", so the recipe
fails trying to locate its license fail like this:
  ERROR: ltp-20180118+gitAUTOINC+7599ff232b-r0 do_populate_lic: QA Issue: ltp:
  LIC_FILES_CHKSUM points to an invalid file: /oe/build/tmp-rpb-glibc/work
  /core2-32-linaro-linux/ltp/20180118+gitAUTOINC+7599ff232b-r0/git/tools
  /pounder21/COPYING [license-checksum]

Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>

(Cherry-picked from commit d076823f180ca430c423226dbbd635a9fa115478)