kselftests: add Python modules needed for BPF test
Test test_offload.py from BPF kselftest requires a bunch of
Python3 modules, else it explodes like:
  Traceback (most recent call last):
    File \"./test_offload.py\", line 16, in <module>
      from datetime import datetime
  ImportError: No module named 'datetime'
  selftests: test_offload.py [FAIL]

Modules needed are:
* python3-argparse
* python3-datetime
* python3-json
* python3-pprint
* python3-subprocess

Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>