distro: rpb: set INIT_MANAGER as systemd
Commit fa8c59c in openembedded-core makes usrmerge a requirement,
in order to make sure it still builds with older releases set the
INIT_MANAGER variable so the configuration is always done right
from the defaultsetup.conf loaded after the distro conf.

Log of build failure:
ERROR: Nothing RPROVIDES 'udev' (...)
systemd RPROVIDES udev but was skipped: missing required distro feature 'usrmerge' (not in DISTRO_FEATURES)
eudev RPROVIDES udev but was skipped: conflicting distro feature 'systemd' (in DISTRO_FEATURES)
NOTE: Runtime target 'udev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['udev']

Signed-off-by: Neil Armstrong <neil.armstrong@linaro.org>